services:
  react-native-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - ANDROID_SDK_ROOT=/usr/local/android-sdk-linux
      - PATH=/usr/local/android-sdk-linux/tools:/usr/local/android-sdk-linux/tools/bin:/usr/local/android-sdk-linux/platform-tools:$PATH
